name: 'upload-debian-pkg'
description: 'upload debian packages to s3'
inputs:
  pkgs:
    description: 'deb filenames to upload'
    required: true
  gpg_private_key:
    description: 'GPG private key exported as an ASCII armored version or its base64 encoding'
    required: true
  gpg_passphrase:
    description: 'Passphrase of the GPG private key'
    required: true
  aws_bucket:
    required: true

runs:
  using: "composite"
  steps:
    - name: Install deps
      shell: bash
      run: apt -y --no-install-recommends install ruby gnupg
    - name: Setup deb-s3
      shell: bash
      run: gem install deb-s3

    - name: Import GPG key
      shell: bash
      run: gpg --batch --import <(echo "${{ inputs.gpg_private_key }}")

    - name: upload packages to s3
      shell: bash
      run: deb-s3 upload --bucket=${{inputs.aws_bucket}} --prefix=1.13 --codename=bookworm --component=main --visibility=nil --force-path-style --sign=B104E10C35895CFAC0F91473C8D3BC80B6F22179 --gpg-options "\-\-pinentry-mode=loopback \-\-no-tty \-\-batch \-\-yes \-\-passphrase ${{ inputs.gpg_passphrase }}" ${{inputs.pkgs}}
